services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - middleware

  middleware:
    build: ./middleware
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - auth-service

  auth-service:
    build: ./microservices/auth-service
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
