version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - "5001:5001"
    networks:
      - microservices

  partner-service:
    build: ./microservices/partner-service
    ports:
      - "5002:5002"
    networks:
      - microservices

  medication-service:
    build: ./microservices/medication-service
    ports:
      - "5003:5003"
    networks:
      - microservices

  affiliate-service:
    build: ./microservices/affiliate-service
    ports:
      - "5004:5004"
    networks:
      - microservices

  reminder-service:
    build: ./microservices/reminder-service
    ports:
      - "5005:5005"
    networks:
      - microservices

  scraper-service:
    build: ./microservices/scraper-service
    ports:
      - "5006:5006"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
